# Makefile - VxWorks Simulator Keyboard Driver src Makefile
#
# Copyright 2013, Wind River Systems, Inc.
#      
# The right to copy, distribute, modify or otherwise make use
# of this software may be licensed only pursuant to the terms
# of an applicable Wind River license agreement.
#
# modification history
# -------------------- 
# 27aug13,y_f  create

DOC_FILES = evdevDrvVxSimKbd.c
OBJS = evdevDrvVxSimKbd.o
LIB_BASE_NAME = evdevDrvVxSimKbd

include $(WIND_KRNL_MK)/rules.library.mk