# Makefile - TI AM335X Touch Screen Driver Makefile
#
# Copyright 2013, Wind River Systems, Inc.
#
# The right to copy, distribute, modify or otherwise make use
# of this software may be licensed only pursuant to the terms
# of an applicable Wind River license agreement.
#
# modification history
# --------------------
# 15aug13,y_f  create

BUILD_DIRS = src
POST_NOBUILD_CDFDIRS = cdf

include $(WIND_KRNL_MK)/rules.layers.mk