# Makefile - Wind River Audio Layer Makefile
#
# Copyright 2013, 2016 Wind River Systems, Inc.
#      
# The right to copy, distribute, modify or otherwise make use
# of this software may be licensed only pursuant to the terms
# of an applicable Wind River license agreement.
#
# modification history
# -------------------- 
# 12jan16,mze  remove dead macros
# 30oct13,y_f  written

POST_NOBUILD_CDFDIRS = cdf

include $(WIND_KRNL_MK)/rules.layers.mk