# Makefile - TI McASP Audio Driver src Makefile
#
# Copyright 2014, Wind River Systems, Inc.
#      
# The right to copy, distribute, modify or otherwise make use
# of this software may be licensed only pursuant to the terms
# of an applicable Wind River license agreement.
#
# modification history
# -------------------- 
# 21mar14,y_f  written

OBJS = audioDrvTiMcAsp.o
LIB_BASE_NAME = audioDrvTiMcAsp

include $(WIND_KRNL_MK)/rules.library.mk