# Makefile - Frame buffer driver demo Layer Makefile
#
# Copyright (c) 2014 Wind River Systems, Inc.
#
# The right to copy, distribute, modify or otherwise make use
# of this software may be licensed only pursuant to the terms
# of an applicable Wind River License agreement.
#
# modification history
# -------------------- 
# 18jun14,yat  Added main demo for dynamic RTP (US11227)
# 24jan14,mgc  Modified for VxWorks 7 release

BUILD_DIRS = main draw
POSTBUILD_RTP_DIRS = main mainso draw
POST_NOBUILD_CDFDIRS = cdf 

include $(WIND_KRNL_MK)/rules.layers.mk
