# Makefile - VxWorks Virtual Pointer Driver src Makefile
#
# Copyright 2014, Wind River Systems, Inc.
#      
# The right to copy, distribute, modify or otherwise make use
# of this software may be licensed only pursuant to the terms
# of an applicable Wind River license agreement.
#
# modification history
# -------------------- 
# 16may14,yat  Add virtual pointer driver. (US24741)

DOC_FILES = evdevDrvVirtualPtr.c
OBJS = evdevDrvVirtualPtr.o
LIB_BASE_NAME = evdevDrvVirtualPtr

include $(WIND_KRNL_MK)/rules.library.mk
