# Makefile - Wind River Graphics Makefile
#
# Copyright (c) 2014 Wind River Systems, Inc.
#
# The right to copy, distribute, modify or otherwise make use
# of this software may be licensed only pursuant to the terms
# of an applicable Wind River License agreement.
#
# modification history
# --------------------
# 24jan14,mgc  Modified for VxWorks 7 release

SHARED_PUBLIC_H_DIRS = h

include $(WIND_KRNL_MK)/rules.layers.mk
