# Makefile - Event Devices Framework Libraries src Makefile
#
# Copyright 2013, Wind River Systems, Inc.
#      
# The right to copy, distribute, modify or otherwise make use
# of this software may be licensed only pursuant to the terms
# of an applicable Wind River license agreement.
#
# modification history
# -------------------- 
# 04jul13,y_f  create

C_SOURCE = $(wildcard *.c)
DOC_FILES = $(C_SOURCE)
OBJS = $(C_SOURCE:.c=.o)
LIB_BASE_NAME = evdevLib

include $(WIND_KRNL_MK)/rules.library.mk