# Makefile - Mesa Layer Makefile
#
# Copyright (c) 2014-2016 Wind River Systems, Inc.
#
# The right to copy, distribute, modify or otherwise make use
# of this software may be licensed only pursuant to the terms
# of an applicable Wind River License agreement.
#
# modification history
# --------------------
# 12jan16,mze  clean up
# 14sep15,yat  Add shared public h (US24710)
# 22dec14,yat  Port Mesa to VxWorks 7 (US24705)

TGT_DIR=$(WIND_BASE)/target

DOC_OPTS = -mg -nostrict -missingok

include $(TGT_DIR)/h/make/defs.library
SUBDIRS = src

include $(TGT_DIR)/h/make/rules.library