# Makefile - Freescale SGTL5000 Audio Codec Driver src Makefile
#
# Copyright 2014, Wind River Systems, Inc.
#      
# The right to copy, distribute, modify or otherwise make use
# of this software may be licensed only pursuant to the terms
# of an applicable Wind River license agreement.
#
# modification history
# -------------------- 
# 05jun14,y_f  written (US41080)

OBJS = audioDrvFslSgtl5000.o
LIB_BASE_NAME = audioDrvFslSgtl5000

include $(WIND_KRNL_MK)/rules.library.mk