# Makefile - Vector Graphics raster Layer Makefile
#
# Copyright (c) 2012, 2014, 2016 Wind River Systems, Inc.
#
# The right to copy, distribute, modify or otherwise make use
# of this software may be licensed only pursuant to the terms
# of an applicable Wind River License agreement.
#
# modification history
# --------------------
# 12jan16,mze  clean up
# 24jan14,mgc  Modified for VxWorks 7 release
# 11may12,rfm  create

TGT_DIR=$(WIND_BASE)/target
DOC_OPTS = -mg -nostrict -missingok

include $(TGT_DIR)/h/make/defs.library
SUBDIRS = src jpeg2vg png2vg

include $(TGT_DIR)/h/make/rules.library