# Makefile - Wind River XML Layer Makefile
#
# Copyright 2013, 2015-2016 Wind River Systems, Inc.
#      
# The right to copy, distribute, modify or otherwise make use
# of this software may be licensed only pursuant to the terms
# of an applicable Wind River license agreement.
#
# modification history
# -------------------- 
# 12jan16,mze  remove dead macros
# 11sep15,yat  add XML user library support for Mesa (US24710)
# 11jul13,f_f  create
 
TGT_DIR=$(WIND_BASE)/target

DOC_OPTS = -mg -nostrict -missingok
include $(TGT_DIR)/h/make/defs.library

SUBDIRS = src

include $(TGT_DIR)/h/make/rules.library

