# Makefile - EETI EXC7200 Series Multi-touch Controller Driver src Makefile
#
# Copyright 2014 Wind River Systems, Inc.
#      
# The right to copy, distribute, modify or otherwise make use
# of this software may be licensed only pursuant to the terms
# of an applicable Wind River license agreement.
#
# modification history
# -------------------- 
# 01dec14,y_f  created (US50218)

DOC_FILES = evdevDrvEetiExc7200.c
OBJS = evdevDrvEetiExc7200.o
LIB_BASE_NAME = evdevDrvEetiExc7200

include $(WIND_KRNL_MK)/rules.library.mk