/* gl2_mangle.h - GLES2 mangle header file */

/*
 * Copyright (c) 2014 Wind River Systems, Inc.
 *
 * The right to copy, distribute, modify or otherwise make use
 * of this software may be licensed only pursuant to the terms
 * of an applicable Wind River License agreement.
 */

/*
modification history
--------------------
22dec14,yat  Add Mesa GLES2 mangle (US24713)
*/

#ifndef __gl2_mangle_h_
#define __gl2_mangle_h_

#define MANGLE_GLES2(api)               m##api
#define glActiveTexture                 MANGLE_GLES2(glActiveTexture)
#define glAttachShader                  MANGLE_GLES2(glAttachShader)
#define glBindAttribLocation            MANGLE_GLES2(glBindAttribLocation)
#define glBindBuffer                    MANGLE_GLES2(glBindBuffer)
#define glBindFramebuffer               MANGLE_GLES2(glBindFramebuffer)
#define glBindRenderbuffer              MANGLE_GLES2(glBindRenderbuffer)
#define glBindTexture                   MANGLE_GLES2(glBindTexture)
#define glBlendColor                    MANGLE_GLES2(glBlendColor)
#define glBlendEquation                 MANGLE_GLES2(glBlendEquation)
#define glBlendEquationSeparate         MANGLE_GLES2(glBlendEquationSeparate)
#define glBlendFunc                     MANGLE_GLES2(glBlendFunc)
#define glBlendFuncSeparate             MANGLE_GLES2(glBlendFuncSeparate)
#define glBufferData                    MANGLE_GLES2(glBufferData)
#define glBufferSubData                 MANGLE_GLES2(glBufferSubData)
#define glCheckFramebufferStatus        MANGLE_GLES2(glCheckFramebufferStatus)
#define glClear                         MANGLE_GLES2(glClear)
#define glClearColor                    MANGLE_GLES2(glClearColor)
#define glClearDepthf                   MANGLE_GLES2(glClearDepthf)
#define glClearStencil                  MANGLE_GLES2(glClearStencil)
#define glColorMask                     MANGLE_GLES2(glColorMask)
#define glCompileShader                 MANGLE_GLES2(glCompileShader)
#define glCompressedTexImage2D          MANGLE_GLES2(glCompressedTexImage2D)
#define glCompressedTexSubImage2D       MANGLE_GLES2(glCompressedTexSubImage2D)
#define glCopyTexImage2D                MANGLE_GLES2(glCopyTexImage2D)
#define glCopyTexSubImage2D             MANGLE_GLES2(glCopyTexSubImage2D)
#define glCreateProgram                 MANGLE_GLES2(glCreateProgram)
#define glCreateShader                  MANGLE_GLES2(glCreateShader)
#define glCullFace                      MANGLE_GLES2(glCullFace)
#define glDeleteBuffers                 MANGLE_GLES2(glDeleteBuffers)
#define glDeleteFramebuffers            MANGLE_GLES2(glDeleteFramebuffers)
#define glDeleteProgram                 MANGLE_GLES2(glDeleteProgram)
#define glDeleteRenderbuffers           MANGLE_GLES2(glDeleteRenderbuffers)
#define glDeleteShader                  MANGLE_GLES2(glDeleteShader)
#define glDeleteTextures                MANGLE_GLES2(glDeleteTextures)
#define glDepthFunc                     MANGLE_GLES2(glDepthFunc)
#define glDepthMask                     MANGLE_GLES2(glDepthMask)
#define glDepthRangef                   MANGLE_GLES2(glDepthRangef)
#define glDetachShader                  MANGLE_GLES2(glDetachShader)
#define glDisable                       MANGLE_GLES2(glDisable)
#define glDisableVertexAttribArray      MANGLE_GLES2(glDisableVertexAttribArray)
#define glDrawArrays                    MANGLE_GLES2(glDrawArrays)
#define glDrawElements                  MANGLE_GLES2(glDrawElements)
#define glEnable                        MANGLE_GLES2(glEnable)
#define glEnableVertexAttribArray       MANGLE_GLES2(glEnableVertexAttribArray)
#define glFinish                        MANGLE_GLES2(glFinish)
#define glFlush                         MANGLE_GLES2(glFlush)
#define glFramebufferRenderbuffer       MANGLE_GLES2(glFramebufferRenderbuffer)
#define glFramebufferTexture2D          MANGLE_GLES2(glFramebufferTexture2D)
#define glFrontFace                     MANGLE_GLES2(glFrontFace)
#define glGenBuffers                    MANGLE_GLES2(glGenBuffers)
#define glGenerateMipmap                MANGLE_GLES2(glGenerateMipmap)
#define glGenFramebuffers               MANGLE_GLES2(glGenFramebuffers)
#define glGenRenderbuffers              MANGLE_GLES2(glGenRenderbuffers)
#define glGenTextures                   MANGLE_GLES2(glGenTextures)
#define glGetActiveAttrib               MANGLE_GLES2(glGetActiveAttrib)
#define glGetActiveUniform              MANGLE_GLES2(glGetActiveUniform)
#define glGetAttachedShaders            MANGLE_GLES2(glGetAttachedShaders)
#define glGetAttribLocation             MANGLE_GLES2(glGetAttribLocation)
#define glGetBooleanv                   MANGLE_GLES2(glGetBooleanv)
#define glGetBufferParameteriv          MANGLE_GLES2(glGetBufferParameteriv)
#define glGetError                      MANGLE_GLES2(glGetError)
#define glGetFloatv                     MANGLE_GLES2(glGetFloatv)
#define glGetFramebufferAttachmentParameteriv MANGLE_GLES2(glGetFramebufferAttachmentParameteriv)
#define glGetIntegerv                   MANGLE_GLES2(glGetIntegerv)
#define glGetProgramiv                  MANGLE_GLES2(glGetProgramiv)
#define glGetProgramInfoLog             MANGLE_GLES2(glGetProgramInfoLog)
#define glGetRenderbufferParameteriv    MANGLE_GLES2(glGetRenderbufferParameteriv)
#define glGetShaderiv                   MANGLE_GLES2(glGetShaderiv)
#define glGetShaderInfoLog              MANGLE_GLES2(glGetShaderInfoLog)
#define glGetShaderPrecisionFormat      MANGLE_GLES2(glGetShaderPrecisionFormat)
#define glGetShaderSource               MANGLE_GLES2(glGetShaderSource)
#define glGetString                     MANGLE_GLES2(glGetString)
#define glGetTexParameterfv             MANGLE_GLES2(glGetTexParameterfv)
#define glGetTexParameteriv             MANGLE_GLES2(glGetTexParameteriv)
#define glGetUniformfv                  MANGLE_GLES2(glGetUniformfv)
#define glGetUniformiv                  MANGLE_GLES2(glGetUniformiv)
#define glGetUniformLocation            MANGLE_GLES2(glGetUniformLocation)
#define glGetVertexAttribfv             MANGLE_GLES2(glGetVertexAttribfv)
#define glGetVertexAttribiv             MANGLE_GLES2(glGetVertexAttribiv)
#define glGetVertexAttribPointerv       MANGLE_GLES2(glGetVertexAttribPointerv)
#define glHint                          MANGLE_GLES2(glHint)
#define glIsBuffer                      MANGLE_GLES2(glIsBuffer)
#define glIsEnabled                     MANGLE_GLES2(glIsEnabled)
#define glIsFramebuffer                 MANGLE_GLES2(glIsFramebuffer)
#define glIsProgram                     MANGLE_GLES2(glIsProgram)
#define glIsRenderbuffer                MANGLE_GLES2(glIsRenderbuffer)
#define glIsShader                      MANGLE_GLES2(glIsShader)
#define glIsTexture                     MANGLE_GLES2(glIsTexture)
#define glLineWidth                     MANGLE_GLES2(glLineWidth)
#define glLinkProgram                   MANGLE_GLES2(glLinkProgram)
#define glPixelStorei                   MANGLE_GLES2(glPixelStorei)
#define glPolygonOffset                 MANGLE_GLES2(glPolygonOffset)
#define glReadPixels                    MANGLE_GLES2(glReadPixels)
#define glReleaseShaderCompiler         MANGLE_GLES2(glReleaseShaderCompiler)
#define glRenderbufferStorage           MANGLE_GLES2(glRenderbufferStorage)
#define glSampleCoverage                MANGLE_GLES2(glSampleCoverage)
#define glScissor                       MANGLE_GLES2(glScissor)
#define glShaderBinary                  MANGLE_GLES2(glShaderBinary)
#define glShaderSource                  MANGLE_GLES2(glShaderSource)
#define glStencilFunc                   MANGLE_GLES2(glStencilFunc)
#define glStencilFuncSeparate           MANGLE_GLES2(glStencilFuncSeparate)
#define glStencilMask                   MANGLE_GLES2(glStencilMask)
#define glStencilMaskSeparate           MANGLE_GLES2(glStencilMaskSeparate)
#define glStencilOp                     MANGLE_GLES2(glStencilOp)
#define glStencilOpSeparate             MANGLE_GLES2(glStencilOpSeparate)
#define glTexImage2D                    MANGLE_GLES2(glTexImage2D)
#define glTexParameterf                 MANGLE_GLES2(glTexParameterf)
#define glTexParameterfv                MANGLE_GLES2(glTexParameterfv)
#define glTexParameteri                 MANGLE_GLES2(glTexParameteri)
#define glTexParameteriv                MANGLE_GLES2(glTexParameteriv)
#define glTexSubImage2D                 MANGLE_GLES2(glTexSubImage2D)
#define glUniform1f                     MANGLE_GLES2(glUniform1f)
#define glUniform1fv                    MANGLE_GLES2(glUniform1fv)
#define glUniform1i                     MANGLE_GLES2(glUniform1i)
#define glUniform1iv                    MANGLE_GLES2(glUniform1iv)
#define glUniform2f                     MANGLE_GLES2(glUniform2f)
#define glUniform2fv                    MANGLE_GLES2(glUniform2fv)
#define glUniform2i                     MANGLE_GLES2(glUniform2i)
#define glUniform2iv                    MANGLE_GLES2(glUniform2iv)
#define glUniform3f                     MANGLE_GLES2(glUniform3f)
#define glUniform3fv                    MANGLE_GLES2(glUniform3fv)
#define glUniform3i                     MANGLE_GLES2(glUniform3i)
#define glUniform3iv                    MANGLE_GLES2(glUniform3iv)
#define glUniform4f                     MANGLE_GLES2(glUniform4f)
#define glUniform4fv                    MANGLE_GLES2(glUniform4fv)
#define glUniform4i                     MANGLE_GLES2(glUniform4i)
#define glUniform4iv                    MANGLE_GLES2(glUniform4iv)
#define glUniformMatrix2fv              MANGLE_GLES2(glUniformMatrix2fv)
#define glUniformMatrix3fv              MANGLE_GLES2(glUniformMatrix3fv)
#define glUniformMatrix4fv              MANGLE_GLES2(glUniformMatrix4fv)
#define glUseProgram                    MANGLE_GLES2(glUseProgram)
#define glValidateProgram               MANGLE_GLES2(glValidateProgram)
#define glVertexAttrib1f                MANGLE_GLES2(glVertexAttrib1f)
#define glVertexAttrib1fv               MANGLE_GLES2(glVertexAttrib1fv)
#define glVertexAttrib2f                MANGLE_GLES2(glVertexAttrib2f)
#define glVertexAttrib2fv               MANGLE_GLES2(glVertexAttrib2fv)
#define glVertexAttrib3f                MANGLE_GLES2(glVertexAttrib3f)
#define glVertexAttrib3fv               MANGLE_GLES2(glVertexAttrib3fv)
#define glVertexAttrib4f                MANGLE_GLES2(glVertexAttrib4f)
#define glVertexAttrib4fv               MANGLE_GLES2(glVertexAttrib4fv)
#define glVertexAttribPointer           MANGLE_GLES2(glVertexAttribPointer)
#define glViewport                      MANGLE_GLES2(glViewport)

#define glEGLImageTargetTexture2DOES    MANGLE_GLES2(glEGLImageTargetTexture2DOES)
#define glEGLImageTargetRenderbufferStorageOES MANGLE_GLES2(glEGLImageTargetRenderbufferStorageOES)
#define glGetProgramBinaryOES           MANGLE_GLES2(glGetProgramBinaryOES)
#define glProgramBinaryOES              MANGLE_GLES2(glProgramBinaryOES)
#define glMapBufferOES                  MANGLE_GLES2(glMapBufferOES)
#define glUnmapBufferOES                MANGLE_GLES2(glUnmapBufferOES)
#define glGetBufferPointervOES          MANGLE_GLES2(glGetBufferPointervOES)
#define glTexImage3DOES                 MANGLE_GLES2(glTexImage3DOES)
#define glTexSubImage3DOES              MANGLE_GLES2(glTexSubImage3DOES)
#define glCopyTexSubImage3DOES          MANGLE_GLES2(glCopyTexSubImage3DOES)
#define glCompressedTexImage3DOES       MANGLE_GLES2(glCompressedTexImage3DOES)
#define glCompressedTexSubImage3DOES    MANGLE_GLES2(glCompressedTexSubImage3DOES)
#define glFramebufferTexture3DOES       MANGLE_GLES2(glFramebufferTexture3DOES)
#define glBindVertexArrayOES            MANGLE_GLES2(glBindVertexArrayOES)
#define glDeleteVertexArraysOES         MANGLE_GLES2(glDeleteVertexArraysOES)
#define glGenVertexArraysOES            MANGLE_GLES2(glGenVertexArraysOES)
#define glIsVertexArrayOES              MANGLE_GLES2(glIsVertexArrayOES)
#define glMultiDrawArraysEXT            MANGLE_GLES2(glMultiDrawArraysEXT)
#define glMultiDrawElementsEXT          MANGLE_GLES2(glMultiDrawElementsEXT)
#define glMapBufferRangeEXT             MANGLE_GLES2(glMapBufferRangeEXT)
#define glFlushMappedBufferRangeEXT     MANGLE_GLES2(glFlushMappedBufferRangeEXT)
#define glDiscardFramebufferEXT         MANGLE_GLES2(glDiscardFramebufferEXT)

#endif /* __gl2_mangle_h_ */
