# Makefile - FocalTech Systems FT5X06 Series Multi-touch Controller Driver src Makefile
#
# Copyright 2014 Wind River Systems, Inc.
#      
# The right to copy, distribute, modify or otherwise make use
# of this software may be licensed only pursuant to the terms
# of an applicable Wind River license agreement.
#
# modification history
# -------------------- 
# 25jul14,y_f  created (US41404)

DOC_FILES = evdevDrvFt5x06.c
OBJS = evdevDrvFt5x06.o
LIB_BASE_NAME = evdevDrvFt5x06

include $(WIND_KRNL_MK)/rules.library.mk