# Makefile - Intel Graphics and Memory Controller frame buffer driver Makefile
#
# Copyright (c) 2014 Wind River Systems, Inc.
#
# The right to copy, distribute, modify or otherwise make use
# of this software may be licensed only pursuant to the terms
# of an applicable Wind River License agreement.
#
# modification history
# --------------------
# 20dec14,qsn  Initial VxWorks 7 release (US48907)

BUILD_DIRS = src
POST_NOBUILD_CFGDIRS = cfg
POST_NOBUILD_CDFDIRS = cdf

include $(WIND_KRNL_MK)/rules.layers.mk
