# Makefile for libDRM
#
# Copyright (c) 2013-2015 Wind River Systems, Inc.
#
# The right to copy, distribute, modify or otherwise make use
# of this software may be licensed only pursuant to the terms
# of an applicable Wind River License agreement.
#
# modification history
# --------------------
# 16jun15,yat  Change to public directory h (US60452)
# 07jan15,yat  Port libDRM to VxWorks 7 (US24705)
# 20nov13,mgc  created

SHARED_PUBLIC_H_DIRS = h
BUILD_DIRS = src
BUILD_USER_DIRS = src

include $(WIND_KRNL_MK)/rules.layers.mk
