# Makefile - VxWorks Virtual Pointer Driver Makefile
#
# Copyright 2014, Wind River Systems, Inc.
#
# The right to copy, distribute, modify or otherwise make use
# of this software may be licensed only pursuant to the terms
# of an applicable Wind River license agreement.
#
# modification history
# --------------------
# 16may14,yat  Add virtual pointer driver. (US24741)

BUILD_DIRS = src
POST_NOBUILD_CDFDIRS = cdf

include $(WIND_KRNL_MK)/rules.layers.mk
