# Makefile - Sample DRM device driver src Makefile
#
# Copyright 2015, Wind River Systems, Inc.
#
# The right to copy, distribute, modify or otherwise make use
# of this software may be licensed only pursuant to the terms
# of an applicable Wind River license agreement.
#
# modification history
# -------------------- 
# 24jul15,yat  Written (US60452)

LIB_BASE_NAME = gfxSampleDrm
include $(WIND_KRNL_MK)/defs.library.mk

OBJS = sample_drv.o

include $(WIND_KRNL_MK)/rules.library.mk
