# Makefile - Splash screen Makefile
#
# Copyright (c) 2014 Wind River Systems, Inc.
#
# The right to copy, distribute, modify or otherwise make use
# of this software may be licensed only pursuant to the terms
# of an applicable Wind River License agreement.
#
# modification history
# --------------------
# 24jan14,mgc  Modified for VxWorks 7 release

OBJS = gfxSplash.o

LIB_BASE_NAME = gfxSplash

include $(WIND_KRNL_MK)/rules.library.mk
