# Makefile - Event Devices Framework Libraries Makefile
#
# Copyright 2013, 2016 Wind River Systems, Inc.
#
# The right to copy, distribute, modify or otherwise make use
# of this software may be licensed only pursuant to the terms
# of an applicable Wind River license agreement.
#
# modification history
# --------------------
# 12jan16,mze  use new macros
# 12nov13,j_x  add cfg
# 26jun13,y_f  create

SHARED_PUBLIC_H_DIRS = h
BUILD_DIRS = src
POST_NOBUILD_CFGDIRS = cfg
POST_NOBUILD_CDFDIRS = cdf

include $(WIND_KRNL_MK)/rules.layers.mk