# Makefile - VxWorks Virtual Keyboard Driver src Makefile
#
# Copyright 2014, Wind River Systems, Inc.
#      
# The right to copy, distribute, modify or otherwise make use
# of this software may be licensed only pursuant to the terms
# of an applicable Wind River license agreement.
#
# modification history
# -------------------- 
# 16may14,yat  Add virtual keyboard driver. (US24741)

DOC_FILES = evdevDrvVirtualKbd.c
OBJS = evdevDrvVirtualKbd.o
LIB_BASE_NAME = evdevDrvVirtualKbd

include $(WIND_KRNL_MK)/rules.library.mk
