# Makefile - TI AM335X Touch Screen Driver src Makefile
#
# Copyright 2013, Wind River Systems, Inc.
#      
# The right to copy, distribute, modify or otherwise make use
# of this software may be licensed only pursuant to the terms
# of an applicable Wind River license agreement.
#
# modification history
# -------------------- 
# 15aug13,y_f  create

DOC_FILES = evdevDrvTiAm335x.c
OBJS = evdevDrvTiAm335x.o
LIB_BASE_NAME = evdevDrvTiAm335x

include $(WIND_KRNL_MK)/rules.library.mk