# Makefile - Vector Graphics GLU Makefile
#
# Copyright (c) 2013-2014 Wind River Systems, Inc.
#
# The right to copy, distribute, modify or otherwise make use
# of this software may be licensed only pursuant to the terms
# of an applicable Wind River License agreement.
#
# modification history
# -------------------- 
# 01a,11may12,rfm  create



TGT_DIR=$(WIND_BASE)/target
DOC_OPTS = -mg -nostrict -missingok

include $(TGT_DIR)/h/make/defs.library
SUBDIRS = libtess

include $(TGT_DIR)/h/make/rules.library