# Makefile - VxWorks Simulator Pointer Driver src Makefile
#
# Copyright 2013, Wind River Systems, Inc.
#      
# The right to copy, distribute, modify or otherwise make use
# of this software may be licensed only pursuant to the terms
# of an applicable Wind River license agreement.
#
# modification history
# -------------------- 
# 26aug13,y_f  create

DOC_FILES = evdevDrvVxSimPtr.c
OBJS = evdevDrvVxSimPtr.o
LIB_BASE_NAME = evdevDrvVxSimPtr

include $(WIND_KRNL_MK)/rules.library.mk