/* gl1_mangle.h - GLES1 mangle header file */

/*
 * Copyright (c) 2014,2016 Wind River Systems, Inc.
 *
 * The right to copy, distribute, modify or otherwise make use
 * of this software may be licensed only pursuant to the terms
 * of an applicable Wind River License agreement.
 */

/*
modification history
--------------------
11jan16,yat  Remove glFrustum
22dec14,yat  Add Mesa GLES1 mangle (US24713)
*/

#ifndef __gl1_mangle_h_
#define __gl1_mangle_h_

#define MANGLE_GLES(api)                m##api
#define glAlphaFunc                     MANGLE_GLES(glAlphaFunc)
#define glActiveTexture                 MANGLE_GLES(glActiveTexture)
#define glAlphaFuncx                    MANGLE_GLES(glAlphaFuncx)
#define glBindBuffer                    MANGLE_GLES(glBindBuffer)
#define glBindTexture                   MANGLE_GLES(glBindTexture)
#define glBlendFunc                     MANGLE_GLES(glBlendFunc)
#define glBufferData                    MANGLE_GLES(glBufferData)
#define glBufferSubData                 MANGLE_GLES(glBufferSubData)
#define glClear                         MANGLE_GLES(glClear)
#define glClearColor                    MANGLE_GLES(glClearColor)
#define glClearColorx                   MANGLE_GLES(glClearColorx)
#define glClearDepthf                   MANGLE_GLES(glClearDepthf)
#define glClearDepthx                   MANGLE_GLES(glClearDepthx)
#define glClearStencil                  MANGLE_GLES(glClearStencil)
#define glClientActiveTexture           MANGLE_GLES(glClientActiveTexture)
#define glClipPlanef                    MANGLE_GLES(glClipPlanef)
#define glClipPlanex                    MANGLE_GLES(glClipPlanex)
#define glColor4f                       MANGLE_GLES(glColor4f)
#define glColor4ub                      MANGLE_GLES(glColor4ub)
#define glColor4x                       MANGLE_GLES(glColor4x)
#define glColorMask                     MANGLE_GLES(glColorMask)
#define glColorPointer                  MANGLE_GLES(glColorPointer)
#define glCompressedTexImage2D          MANGLE_GLES(glCompressedTexImage2D)
#define glCompressedTexSubImage2D       MANGLE_GLES(glCompressedTexSubImage2D)
#define glCopyTexImage2D                MANGLE_GLES(glCopyTexImage2D)
#define glCopyTexSubImage2D             MANGLE_GLES(glCopyTexSubImage2D)
#define glCullFace                      MANGLE_GLES(glCullFace)
#define glDeleteBuffers                 MANGLE_GLES(glDeleteBuffers)
#define glDeleteTextures                MANGLE_GLES(glDeleteTextures)
#define glDepthFunc                     MANGLE_GLES(glDepthFunc)
#define glDepthMask                     MANGLE_GLES(glDepthMask)
#define glDepthRangef                   MANGLE_GLES(glDepthRangef)
#define glDepthRangex                   MANGLE_GLES(glDepthRangex)
#define glDisable                       MANGLE_GLES(glDisable)
#define glDisableClientState            MANGLE_GLES(glDisableClientState)
#define glDrawArrays                    MANGLE_GLES(glDrawArrays)
#define glDrawElements                  MANGLE_GLES(glDrawElements)
#define glEnable                        MANGLE_GLES(glEnable)
#define glEnableClientState             MANGLE_GLES(glEnableClientState)
#define glFinish                        MANGLE_GLES(glFinish)
#define glFlush                         MANGLE_GLES(glFlush)
#define glFogf                          MANGLE_GLES(glFogf)
#define glFogfv                         MANGLE_GLES(glFogfv)
#define glFogx                          MANGLE_GLES(glFogx)
#define glFogxv                         MANGLE_GLES(glFogxv)
#define glFrontFace                     MANGLE_GLES(glFrontFace)
#define glFrustumf                      MANGLE_GLES(glFrustumf)
#define glFrustumx                      MANGLE_GLES(glFrustumx)
#define glGenBuffers                    MANGLE_GLES(glGenBuffers)
#define glGenTextures                   MANGLE_GLES(glGenTextures)
#define glGetBooleanv                   MANGLE_GLES(glGetBooleanv)
#define glGetBufferParameteriv          MANGLE_GLES(glGetBufferParameteriv)
#define glGetClipPlanef                 MANGLE_GLES(glGetClipPlanef)
#define glGetClipPlanex                 MANGLE_GLES(glGetClipPlanex)
#define glGetError                      MANGLE_GLES(glGetError)
#define glGetFixedv                     MANGLE_GLES(glGetFixedv)
#define glGetFloatv                     MANGLE_GLES(glGetFloatv)
#define glGetIntegerv                   MANGLE_GLES(glGetIntegerv)
#define glGetLightfv                    MANGLE_GLES(glGetLightfv)
#define glGetLightxv                    MANGLE_GLES(glGetLightxv)
#define glGetMaterialfv                 MANGLE_GLES(glGetMaterialfv)
#define glGetMaterialxv                 MANGLE_GLES(glGetMaterialxv)
#define glGetPointerv                   MANGLE_GLES(glGetPointerv)
#define glGetString                     MANGLE_GLES(glGetString)
#define glGetTexEnvfv                   MANGLE_GLES(glGetTexEnvfv)
#define glGetTexEnviv                   MANGLE_GLES(glGetTexEnviv)
#define glGetTexEnvxv                   MANGLE_GLES(glGetTexEnvxv)
#define glGetTexParameterfv             MANGLE_GLES(glGetTexParameterfv)
#define glGetTexParameteriv             MANGLE_GLES(glGetTexParameteriv)
#define glGetTexParameterxv             MANGLE_GLES(glGetTexParameterxv)
#define glHint                          MANGLE_GLES(glHint)
#define glIsBuffer                      MANGLE_GLES(glIsBuffer)
#define glIsEnabled                     MANGLE_GLES(glIsEnabled)
#define glIsTexture                     MANGLE_GLES(glIsTexture)
#define glLightModelf                   MANGLE_GLES(glLightModelf)
#define glLightModelfv                  MANGLE_GLES(glLightModelfv)
#define glLightModelx                   MANGLE_GLES(glLightModelx)
#define glLightModelxv                  MANGLE_GLES(glLightModelxv)
#define glLightf                        MANGLE_GLES(glLightf)
#define glLightfv                       MANGLE_GLES(glLightfv)
#define glLightx                        MANGLE_GLES(glLightx)
#define glLightxv                       MANGLE_GLES(glLightxv)
#define glLineWidth                     MANGLE_GLES(glLineWidth)
#define glLineWidthx                    MANGLE_GLES(glLineWidthx)
#define glLoadIdentity                  MANGLE_GLES(glLoadIdentity)
#define glLoadMatrixf                   MANGLE_GLES(glLoadMatrixf)
#define glLoadMatrixx                   MANGLE_GLES(glLoadMatrixx)
#define glLogicOp                       MANGLE_GLES(glLogicOp)
#define glMaterialf                     MANGLE_GLES(glMaterialf)
#define glMaterialfv                    MANGLE_GLES(glMaterialfv)
#define glMaterialx                     MANGLE_GLES(glMaterialx)
#define glMaterialxv                    MANGLE_GLES(glMaterialxv)
#define glMatrixMode                    MANGLE_GLES(glMatrixMode)
#define glMultMatrixf                   MANGLE_GLES(glMultMatrixf)
#define glMultMatrixx                   MANGLE_GLES(glMultMatrixx)
#define glMultiTexCoord4f               MANGLE_GLES(glMultiTexCoord4f)
#define glMultiTexCoord4x               MANGLE_GLES(glMultiTexCoord4x)
#define glNormal3f                      MANGLE_GLES(glNormal3f)
#define glNormal3x                      MANGLE_GLES(glNormal3x)
#define glNormalPointer                 MANGLE_GLES(glNormalPointer)
#define glOrthof                        MANGLE_GLES(glOrthof)
#define glOrthox                        MANGLE_GLES(glOrthox)
#define glPixelStorei                   MANGLE_GLES(glPixelStorei)
#define glPointParameterf               MANGLE_GLES(glPointParameterf)
#define glPointParameterfv              MANGLE_GLES(glPointParameterfv)
#define glPointParameterx               MANGLE_GLES(glPointParameterx)
#define glPointParameterxv              MANGLE_GLES(glPointParameterxv)
#define glPointSize                     MANGLE_GLES(glPointSize)
#define glPointSizex                    MANGLE_GLES(glPointSizex)
#define glPolygonOffset                 MANGLE_GLES(glPolygonOffset)
#define glPolygonOffsetx                MANGLE_GLES(glPolygonOffsetx)
#define glPopMatrix                     MANGLE_GLES(glPopMatrix)
#define glPushMatrix                    MANGLE_GLES(glPushMatrix)
#define glReadPixels                    MANGLE_GLES(glReadPixels)
#define glRotatef                       MANGLE_GLES(glRotatef)
#define glRotatex                       MANGLE_GLES(glRotatex)
#define glSampleCoverage                MANGLE_GLES(glSampleCoverage)
#define glSampleCoveragex               MANGLE_GLES(glSampleCoveragex)
#define glScalef                        MANGLE_GLES(glScalef)
#define glScalex                        MANGLE_GLES(glScalex)
#define glScissor                       MANGLE_GLES(glScissor)
#define glShadeModel                    MANGLE_GLES(glShadeModel)
#define glStencilFunc                   MANGLE_GLES(glStencilFunc)
#define glStencilMask                   MANGLE_GLES(glStencilMask)
#define glStencilOp                     MANGLE_GLES(glStencilOp)
#define glTexCoordPointer               MANGLE_GLES(glTexCoordPointer)
#define glTexEnvf                       MANGLE_GLES(glTexEnvf)
#define glTexEnvfv                      MANGLE_GLES(glTexEnvfv)
#define glTexEnvi                       MANGLE_GLES(glTexEnvi)
#define glTexEnviv                      MANGLE_GLES(glTexEnviv)
#define glTexEnvx                       MANGLE_GLES(glTexEnvx)
#define glTexEnvxv                      MANGLE_GLES(glTexEnvxv)
#define glTexImage2D                    MANGLE_GLES(glTexImage2D)
#define glTexParameterf                 MANGLE_GLES(glTexParameterf)
#define glTexParameterfv                MANGLE_GLES(glTexParameterfv)
#define glTexParameteri                 MANGLE_GLES(glTexParameteri)
#define glTexParameteriv                MANGLE_GLES(glTexParameteriv)
#define glTexParameterx                 MANGLE_GLES(glTexParameterx)
#define glTexParameterxv                MANGLE_GLES(glTexParameterxv)
#define glTexSubImage2D                 MANGLE_GLES(glTexSubImage2D)
#define glTranslatef                    MANGLE_GLES(glTranslatef)
#define glTranslatex                    MANGLE_GLES(glTranslatex)
#define glVertexPointer                 MANGLE_GLES(glVertexPointer)
#define glViewport                      MANGLE_GLES(glViewport)

#endif /* __gl1_mangle_h_ */
