# Makefile - TI TSC2004 Touch Screen Driver src Makefile
#
# Copyright 2013, Wind River Systems, Inc.
#      
# The right to copy, distribute, modify or otherwise make use
# of this software may be licensed only pursuant to the terms
# of an applicable Wind River license agreement.
#
# modification history
# -------------------- 
# 23jul13,y_f  create

DOC_FILES = evdevDrvTiTsc2004.c
OBJS = evdevDrvTiTsc2004.o
LIB_BASE_NAME = evdevDrvTiTsc2004

include $(WIND_KRNL_MK)/rules.library.mk