# Makefile - Intel Graphics and Memory Controller frame buffer driver Makefile
#
# Copyright (c) 2015 Wind River Systems, Inc.
#
# The right to copy, distribute, modify or otherwise make use
# of this software may be licensed only pursuant to the terms
# of an applicable Wind River License agreement.
#
# modification history
# --------------------
# 14sep15,yat  Rename OBJS file (US66034)
# 11mar15,yat  Add show support (US55410)

OBJS = gfxItlGmcShow.o 

EXTRA_INCLUDE += -I../../h

LIB_BASE_NAME = gfxItlGmcFbShow

include $(WIND_KRNL_MK)/rules.library.mk
