# Makefile - Wind River Graphics frame buffer driver interface Makefile
#
# Copyright (c) 2014-2016 Wind River Systems, Inc.
#
# The right to copy, distribute, modify or otherwise make use
# of this software may be licensed only pursuant to the terms
# of an applicable Wind River License agreement.
#
# modification history
# --------------------
# 24feb16,yat  Remove unused BUILD_USER_DIRS (US75033)
# 16apr15,yat  Add BUILD_DIRS and BUILD_USER_DIRS for fbdev docs fix (V7GFX-245)
# 24jan14,mgc  Modified for VxWorks 7 release


SHARED_PUBLIC_H_DIRS = h
BUILD_DIRS = src
POST_NOBUILD_CFGDIRS = cfg
POST_NOBUILD_CDFDIRS = cdf

include $(WIND_KRNL_MK)/rules.layers.mk
